#!/bin/bash

# Script by Adrian Chmiel (chmieladr)
# Features CopyQ clipboard manager available on the following GitHub page:
# https://github.com/hluk/CopyQ

# Run once!
# Requires the Flatpak package manager

# Install the CopyQ clipboard manager
flatpak install flathub com.github.hluk.copyq

# Run CopyQ
flatpak run com.github.hluk.copyq &

# Confirmation message
echo "CopyQ has been successfully installed and launched!"
