#!/bin/sh
# Script by Adrian Chmiel (chmieladr)
# Run once!

# Add the config
SRC=~/.bashrc
echo "" >>$SRC
echo "# Automatic coloring" >>$SRC
echo "alias ls='ls --color=auto'" >>$SRC
echo "alias grep='grep --color=auto'" >>$SRC

# Reload the current terminal session
source ~/.bashrc

# Confirmation message
echo "Autocolor has been toggled on for 'ls' and 'grep' commands!"
