#!/bin/bash

# Script by Adrian Chmiel (chmieladr)
# Features CopyQ clipboard manager available on the following GitHub page:
# https://github.com/hluk/CopyQ

# Run once!
# Requires the Flatpak package manager

# Install the CopyQ clipboard manager
flatpak install flathub com.github.hluk.copyq

# Run CopyQ
flatpak run com.github.hluk.copyq &

# Add an entry to .bashrc to run CopyQ on startup
SRC=~/.bashrc
echo "" >>$SRC
echo "# Start CopyQ clipboard manager" >>$SRC
echo "flatpak run com.github.hluk.copyq" >>$SRC

# Confirmation message
echo "Clipboard manager has been successfully replaced wtih CopyQ!"