#!/bin/bash

# Script by Adrian Chmiel (chmieladr)
# Based on the following thread:
# https://www.reddit.com/r/linux_gaming/comments/or1g40/changing_mouse_debounce_time_on_arch_linux/

# Run once!

# Create the necessary config file
sudo mkdir -p /etc/libinput
QUIRKS="/etc/libinput/local-overrides.quirks"
sudo touch $QUIRKS
echo "[Never Debounce]" | sudo tee -a $QUIRKS > /dev/null
echo "MatchUdevType=mouse" | sudo tee -a $QUIRKS > /dev/null
echo "ModelBouncingKeys=1" | sudo tee -a $QUIRKS > /dev/null

# Confirmation message
echo "Debounce successfully modified! Restart the system to take effect!"
echo "(sudo reboot)"
